# -*- coding: utf-8 -*-
"""Ajeng Ayu Maulidiah_012_tugas data casting.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1g99Z8hBZobf4nOVcdshaRx2QBHKM9glv

*   Nama: Ajeng Ayu Maulidiah
*   Npm: 2451012012

**DATA CASTING**
"""

nama = 'Budi'
usia = 20
lajang = True

print(type(nama))
print(type(usia))
print(type(lajang))

"""**Konversi Tipe Data**"""

usia = input('Masukkan usia anda:')
print(type(usia))

panjang = input('Masukkan panjang: ')
lebar = input('Masukkan lebar: ')

print('Luas =', panjang * lebar)

a = 10 / 2
print(type(a))

b = 1 / 2
print(type(b))

kata = 'Jeruk' *5

print(kata)
print(type(kata))

nama = 'wudi'
tahun_lahir = 2000

print(nama +' lahir di tahun '+ str(tahun_lahir))

panjang = int(input('Masukkan panjang:'))
lebar = float(input('Masukkan lebar:'))

print('Luas =', panjang * lebar)